function write_gephi(file_name, Cost, Class)

c = [0 0 0; 255 0 0; 0 255 0; 0 0 255]; % colormap
%c = [0 0 0; 0 0 0; 0 0 0; 0 0 0]; % colormap

pretext = ['<?xml version="1.0" encoding="UTF-8"?>\n',...
	'<gexf xmlns="http://www.gexf.net/1.2draft" version="1.2" xmlns:viz="http://www.gexf.net/1.2draft/viz" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gexf.net/1.2draft http://www.gexf.net/1.2draft/gexf.xsd">\n',...
	'<meta lastmodifieddate="2011-10-16">\n',...
	'<creator>Gephi 0.8</creator>\n',...
	'<description></description>\n',...
	'</meta>\n',...
	'<graph defaultedgetype="undirected" timeformat="double" mode="dynamic">\n',...
	'<attributes class="node" mode="static">\n',...
	'<attribute id="type" title="type" type="string"></attribute>\n',...
	'<attribute id="xcoord" title="xcoord" type="double"></attribute>\n',...
	'<attribute id="ycoord" title="ycoord" type="double"></attribute>\n',...
	'<attribute id="category" title="category" type="string"></attribute>\n',...
	'<attribute id="modularity_class" title="Modularity Class" type="integer">\n',...
	'<default>0</default>\n',...
	'</attribute>\n',...
	'<attribute id="eigencentrality" title="Eigenvector Centrality" type="double">\n',...
	'<default>0.0</default>\n',...
	'</attribute>\n',...
	'<attribute id="indegree" title="In Degree" type="integer">\n',...
	'<default>0</default>\n',...
	'</attribute>\n',...
	'<attribute id="outdegree" title="Out Degree" type="integer">\n',...
	'<default>0</default>\n',...
	'</attribute>\n',...
	'<attribute id="degree" title="Degree" type="integer">\n',...
	'<default>0</default>\n',...
	'</attribute>\n',...
	'<attribute id="weighted degree" title="Weighted Degree" type="integer">\n',...
	'<default>0</default>\n',...
	'</attribute>\n',...
	'</attributes>\n'];
    node_text = '<nodes>\n'; 
    for i = 1:size(Class,1)
        node_text = [node_text, '<node id="', num2str(i) ,'" label="',...
                num2str(i), '">\n',...
              '<viz:color r="',num2str(c(Class(i),1)),'" g="',num2str(c(Class(i),2)),'" b="',num2str(c(Class(i),3)),'"></viz:color>\n',...
              '</node>\n'];
    end
    node_text = [node_text, '</nodes>\n'];    
    edge_text = '<edges>\n';
    for i = 1:size(Cost,1)
        for j = i:size(Cost,2)
            if Cost(i,j) == 0
                continue;
            end
            edge_text = [edge_text, '<edge id="',...
                  num2str((i-1)*size(Cost,1)+j),...
                  '" source="',num2str(i),'" target="',num2str(j),'">\n',...
                  '<attvalues>\n',...
                    '<attvalue for="weight" value="',num2str(Cost(i,j)),'"></attvalue>\n',...
                  '</attvalues>\n',...
               '</edge>\n'];
        end
    end
    edge_text = [edge_text, '</edges>\n'];
post_text = ['</graph>\n',...
'</gexf>\n'];
file_text = [pretext, node_text, edge_text, post_text];
fileID = fopen(file_name,'wt');
fprintf(fileID, file_text);


